// packages/solvere-core/src/registry.ts

export const FINDING_CODES = {
  RF_NEG: "RF_NEG",
  RES_NEG: "RES_NEG",
  RESERVE_LOW: "RESERVE_LOW",
  APT_MIN: "APT_MIN",
  AREA_ZERO: "AREA_ZERO",
  PERIOD_INV: "PERIOD_INV",
  NO_COSTS: "NO_COSTS",
  COST_CAT_MISSING: "COST_CAT_MISSING",
  COST_CAT_OTHER: "COST_CAT_OTHER",
  NO_INCOME: "NO_INCOME",
  INV_NONE_THIS_YEAR: "INV_NONE_THIS_YEAR",
  INV_NAME_MISSING: "INV_NAME_MISSING",
  INV_COST_ZERO: "INV_COST_ZERO",
  INV_UNDER: "INV_UNDER",
  INV_OVER: "INV_OVER",
  NET_SURPLUS: "NET_SURPLUS",
  ALL_OK: "ALL_OK",
} as const;

export const ACTION_CODES = {
  INCREASE_REPAIR_FUND_RATE_SMALL: "INCREASE_REPAIR_FUND_RATE_SMALL",
  INCREASE_REPAIR_FUND_RATE_MEDIUM: "INCREASE_REPAIR_FUND_RATE_MEDIUM",
  INCREASE_RESERVE_PLANNED_EUR_SMALL: "INCREASE_RESERVE_PLANNED_EUR_SMALL",
  INCREASE_RESERVE_PLANNED_EUR_MEDIUM: "INCREASE_RESERVE_PLANNED_EUR_MEDIUM",
  SET_RESERVE_TO_REQUIRED: "SET_RESERVE_TO_REQUIRED",
} as const;

export const PRESET_CODES = {
  BALANCED: "BALANCED",
  CONSERVATIVE: "CONSERVATIVE",
  LOAN_FRIENDLY: "LOAN_FRIENDLY",
} as const;
